junior:
  model_id: "deepseek-r1-1_5b"   # или любая ≤3B
  max_new_tokens: 64
  temperature: 0.2
  endpoint: "https://api.your-llm-provider.example/v1/chat/completions"
senior:
  provider: "transformers"
  model_id: "mistralai/Mistral-7B-Instruct-v0.3"
  temperature: 0.7
  max_new_tokens: 512
  stop: ["\n\n"]
