baseline_levels:
  dopamine: 6
  serotonin: 6
  norepinephrine: 4
  acetylcholine: 5
  gaba: 4
  glutamate: 6
  endorphins: 5
  oxytocin: 6
  vasopressin: 3
  histamine: 4

bias_map:
  dopamine:
    - humor
    - creativity
    - length
  serotonin:
    - warmth
    - politeness
  norepinephrine:
    - focus
    - brevity
    - precision
  acetylcholine:
    - structure
    - clarify
  gaba:
    - calmness
    - reduced arousal
  glutamate:
    - memory encoding
    - detail
  endorphins:
    - positivity
    - comforting tone
  oxytocin:
    - bonding
    - group-inclusive language
  vasopressin:
    - protective
    - assertive tone
  histamine:
    - alertness
    - energy
    - short sentences
