defaults:
  top_k: 6
  rerank_top_k: 3
  window_days: 60
routes:
  task:     { targets: [temp, short, long] }
  ask:      { targets: [temp, short] }
  smalltalk:{ targets: [short, jokes] }
  joke:     { targets: [jokes] }
